[package]
name = "boringssl"
description = "BoringSSL bindings"
version = "0.0.1"
authors = ["js <js@webtun.org>"]
license = "MIT/Apache-2.0"
homepage = "http://webtun.org"
repository = "https://github.com/webtun/boringssl"

[dependencies]
